### ISSUE TITLE
Use docker for migrations

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/schema#16]
Currently in the `SETUP.md` it is advised to use `migrate` directly from the command line.

This is a bit cumbersome, since it complicates the tool chain for new developers (and old ones alike). Have a look at their [Docker usage section](https://github.com/golang-migrate/migrate#docker-usage).

- [ ]  Use the `docker run -it --rm` variant in `SETUP.md`
- [ ] Remove `migrate` as a hard dependency

**Comment by fgehrlicher** [comment]
Can I take this up?

**Comment by Fohlen** [comment]
Definitely!
