### ISSUE TITLE
Use docker for psql

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/schema#17]
In the `SETUP.md` currently `psql` is a hard requirement. It is possible to use `psql` [directly from the container](https://hub.docker.com/_/postgres). In order to do so, we also need to mount the `fixtures` folder into the container.

- [ ] Rewrite the `SETUP.md` to use `docker run -it --rm` variant of `psql`
- [ ] Remove `psql` as a hard requirement

**Comment by fgehrlicher** [comment]
Can I take this up?

**Comment by Fohlen** [comment]
Hey, yes, I'd love to see your PR! Thanks for taking it on.

**Comment by Fohlen** [comment]
If you want to reference the `db` host I believe you can use [exec](https://docs.docker.com/compose/reference/exec/) to resolve the address (instead of localhost)
