### ISSUE TITLE
Correctly set the BASE_URL in production

### ISSUE THREAD

**Issue by Fohlen** [eventzimmer/schema#18]
Swagger documentation tries to connect to `localhost:3000` in production. Look this up in their Docker image, change the config (`docker-compose.prod.yml`). Ask @Fohlen for a redeploy.

**Comment by brennerm** [comment]
Hey @Fohlen, correct me if I'm wrong but I believe you already using the correct values but the wrong environment variable.

Both docker-compose configs set a URL variable ([prod](https://github.com/eventzimmer/schema/blob/master/docker-compose.prod.yml#L41) / [dev](https://github.com/eventzimmer/schema/blob/master/docker-compose.dev.yml#L13)) which I think should be BASE_URL. Let me know if you agree and I'll create a PR fixing it.

**Comment by Fohlen** [comment]
Hey @brennerm and thanks for having a look at this! 🥂 
I found the [swagger-ui configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md) to be quite confusing, to be honest. If you know the correct way to set the URL I'd be really happy about a PR!

**Comment by brennerm** [comment]
Took a further look into this topic and everything seems fine for me. Visiting https://docs.eventzimmer.de/ displays the API definition retrieved from https://api.eventzimmer.de. Can you describe your issue in more detail?

**Comment by Fohlen** [comment]
Hey @brennerm I should have been more in-detail. You can try this out:

- visit `docs.eventzimmer.de`
- the schema will get loaded from `api.eventzimmer.de`
- try to use any of the functionality, e.g: `/events`
- press "try out"
- press "execute"
- the query will fail because it is fired against `0.0.0.0:3000` (which is obviously wrong)

**Comment by Fohlen** [comment]
This is really odd behaviour in `swagger-ui` and frankly their `Docker` environment documentation is **not** helpful.

**Comment by Fohlen** [comment]
Closed by #32
